import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import useSWR from "swr";

export default function () {
  let {
    query: { category },
  } = useRouter();

  const { data } = useSWR(`/api/category/${category}`, url => axios.get(url).then(res => res.data), { suspense: true });

  return (
    <div>
      <Head>
        <title>{category}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen  h-screen flex flex-col ml-56 p-10">
        <div className="">{category}</div>
        <div>{JSON.stringify(data)}</div>
      </div>
    </div>
  );
}
