import Head from "next/head";

export default function () {
  return (
    <div>
      <Head>
        <title>Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen  h-screen flex flex-col ml-56 p-10">
        <div className="">This is the search page</div>
      </div>
    </div>
  );
}
